### ISSUE TITLE
Enable "discussions" module

### ISSUE THREAD

**Issue by savchenko** [Ukraine-IT-Army/Info#2]
Can someone please enable "discussions"? Either here or create a separate repository.

**Comment by CrisisHD23** [comment]
discussions module enabled

**Comment by savchenko** [comment]
> discussions module enabled

See https://github.com/Ukraine-IT-Army/Info/discussions/7


Might also delete the intro topic: https://github.com/Ukraine-IT-Army/Info/discussions/4
